version: "3.7"
services:
  hapi-fhir:
    container_name: "hapi"
    image: hapiproject/hapi:v5.6.0
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - hapi-data:/data/hapi
      - ${PWD}/my-application.yaml:/data/hapi/application.yaml
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
volumes:
  hapi-data: