.PHONY: all clean

all: POLAR_Testdaten_Original_UKB-UKB-0001-UKB-0015.json.zip POLAR_Testdaten_Original_UKE-UKE-0001-UKE-0020.json.zip POLAR_Testdaten_Original_UKFAU-UKFAU-0001-UKFAU-0011.json.zip POLAR_Testdaten_Original_UKFR-UKFR-0001-UKFR-0010.json.zip POLAR_Testdaten_Original_UKSH-UKSH-0001-UKSH-0005.json.zip
clean: 
	rm -f *.zip  *.json

POLAR_Testdaten_Original_UKSH-UKSH-0001-UKSH-0005.json.zip:
	wget https://github.com/medizininformatik-initiative/kerndatensatz-testdaten/raw/master/Test_Data/Polar/$@
	unzip $@

POLAR_Testdaten_Original_UKB-UKB-0001-UKB-0015.json.zip: 
	wget https://github.com/medizininformatik-initiative/kerndatensatz-testdaten/raw/master/Test_Data/Polar/$@
	unzip $@

POLAR_Testdaten_Original_UKE-UKE-0001-UKE-0020.json.zip: 
	wget https://github.com/medizininformatik-initiative/kerndatensatz-testdaten/raw/master/Test_Data/Polar/$@
	unzip $@
	
POLAR_Testdaten_Original_UKFAU-UKFAU-0001-UKFAU-0011.json.zip:
	wget https://github.com/medizininformatik-initiative/kerndatensatz-testdaten/raw/master/Test_Data/Polar/$@
	unzip $@

POLAR_Testdaten_Original_UKFR-UKFR-0001-UKFR-0010.json.zip:
	wget https://github.com/medizininformatik-initiative/kerndatensatz-testdaten/raw/master/Test_Data/Polar/$@
	unzip $@
